"use client";

import { useEffect, useState } from "react";
import { useTasks } from "@/hooks/use-tasks";
import { useAuth } from "@/hooks/use-auth";
import { Pill, Printer, Search, MapPin, Filter, PackageCheck, Clock } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { toast } from "sonner";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Intervention } from "@/lib/schemas";

export default function PharmacistDashboard() {
  const { tasks, isLoading, updateTask, fetchTasks } = useTasks();
  const { user } = useAuth();
  const [isPrinting, setIsPrinting] = useState(false);
  const [searchTerm, setSearchTerm] = useState("");

  useEffect(() => {
    fetchTasks("pending");
  }, [fetchTasks]);

  const medTasks = (tasks as Intervention[]).filter(t =>
    t.type === "medication" &&
    (t.description.toLowerCase().includes(searchTerm.toLowerCase()) ||
      t.roomNumber?.toLowerCase().includes(searchTerm.toLowerCase()))
  );

  const handlePrint = () => {
    setIsPrinting(true);
    setTimeout(() => {
      window.print();
      setIsPrinting(false);
    }, 500);
  };

  const handleFulfill = async (id: string) => {
    try {
      await updateTask(id, "completed");
      toast.success("Medication fulfillment confirmed");
      fetchTasks("pending");
    } catch (err) {
      const msg = err instanceof Error ? err.message : "Fulfillment failed";
      toast.error(msg);
    }
  };

  return (
    <div className="space-y-8 print:p-0">
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 print:hidden">
        <div className="flex items-center gap-4">
          <div className="p-4 bg-primary/10 rounded-2xl shadow-inner">
            <Pill className="h-8 w-8 text-primary" />
          </div>
          <div>
            <h1 className="text-4xl font-black tracking-tight">Pharmacy Fulfillment</h1>
            <p className="text-muted-foreground font-medium">Dispensing queue for {user?.username}. {medTasks.length} units pending.</p>
          </div>
        </div>
        <div className="flex items-center gap-3">
          <Button variant="outline" className="rounded-xl border-2 h-11 font-bold gap-2" onClick={handlePrint} disabled={isPrinting}>
            <Printer className="h-4 w-4" />
            {isPrinting ? "Preparing..." : "Print Manifest"}
          </Button>
          <Button className="rounded-xl shadow-lg shadow-primary/20 h-11 font-bold">
            Inventory Check
          </Button>
        </div>
      </div>

      {/* Printable Header */}
      <div className="hidden print:block border-b-2 border-foreground pb-6 mb-8">
        <div className="flex justify-between items-start">
          <div>
            <h1 className="text-3xl font-black uppercase tracking-tighter">Pharmacy Delivery Manifest</h1>
            <p className="text-sm font-bold text-muted-foreground">Central General Hospital — Clinical Pharmacy Division</p>
          </div>
          <div className="text-right text-xs font-bold">
            <p>Shift Date: {new Date().toLocaleDateString()}</p>
            <p>Generated By: {user?.fullName || user?.username}</p>
          </div>
        </div>
      </div>

      <Card className="rounded-[2.5rem] border-none shadow-xl shadow-muted/30 overflow-hidden bg-card print:shadow-none print:border-foreground print:border-t-2 print:rounded-none">
        <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-7 border-b bg-muted/5 print:hidden">
          <div>
            <CardTitle className="text-xl font-bold">Medication Preparation Queue</CardTitle>
            <CardDescription className="font-medium text-xs uppercase tracking-widest mt-1">Dispensing protocols & unit-dose tracking</CardDescription>
          </div>
          <div className="flex items-center gap-3">
            <div className="relative">
              <Search className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-muted-foreground" />
              <Input
                placeholder="Search medications..."
                className="pl-9 h-11 w-[250px] bg-muted/50 border-none rounded-xl font-medium"
                value={searchTerm}
                onChange={(e) => setSearchTerm(e.target.value)}
              />
            </div>
            <Button variant="outline" size="icon" className="h-11 w-11 rounded-xl border-2"><Filter className="h-4 w-4" /></Button>
          </div>
        </CardHeader>
        <CardContent className="p-0">
          {isLoading ? (
            <div className="text-center py-20 flex flex-col items-center gap-4 print:hidden">
              <div className="animate-spin rounded-full h-10 w-10 border-b-2 border-primary"></div>
              <p className="text-muted-foreground font-medium">Fetching pharmacy records...</p>
            </div>
          ) : (
            <div className="overflow-x-auto">
              <Table>
                <TableHeader className="bg-muted/30 print:bg-muted/50">
                  <TableRow className="print:border-foreground">
                    <TableHead className="px-8 py-5 text-[10px] font-black uppercase tracking-widest">Target Room</TableHead>
                    <TableHead className="py-5 text-[10px] font-black uppercase tracking-widest">Instruction / Dosage</TableHead>
                    <TableHead className="py-5 text-[10px] font-black uppercase tracking-widest">Scheduled Time</TableHead>
                    <TableHead className="px-8 py-5 text-right text-[10px] font-black uppercase tracking-widest print:hidden">Fulfillment</TableHead>
                    <TableHead className="hidden print:table-cell py-5 text-[10px] font-black uppercase tracking-widest">Sign-off</TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody>
                  {medTasks.map((task) => (
                    <TableRow key={task.id} className="hover:bg-muted/10 transition-colors border-b last:border-0 group print:border-foreground">
                      <TableCell className="px-8 py-6">
                        <div className="flex items-center gap-3">
                          <div className="h-10 w-10 rounded-xl bg-primary/5 flex items-center justify-center print:hidden">
                            <MapPin className="h-4 w-4 text-primary" />
                          </div>
                          <span className="font-black text-xl">Room {task.roomNumber}</span>
                        </div>
                      </TableCell>
                      <TableCell>
                        <div className="flex flex-col">
                          <span className="font-bold text-lg text-foreground/80">{task.description}</span>
                          <span className="text-[10px] font-black text-muted-foreground uppercase tracking-wider">Unit-Dose Protocol</span>
                        </div>
                      </TableCell>
                      <TableCell>
                        <div className="flex items-center gap-2">
                          <Clock className="h-4 w-4 text-muted-foreground print:hidden" />
                          <span className="font-bold">
                            {new Date(task.targetTime).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}
                          </span>
                        </div>
                      </TableCell>
                      <TableCell className="px-8 text-right print:hidden">
                        <Button
                          size="sm"
                          variant="ghost"
                          className="rounded-xl h-10 px-6 font-black text-primary hover:bg-primary/10 transition-all hover:scale-105"
                          onClick={() => handleFulfill(task.id)}
                        >
                          <PackageCheck className="h-5 w-5 mr-2" />
                          Mark Ready
                        </Button>
                      </TableCell>
                      <TableCell className="hidden print:table-cell py-6">
                        <div className="w-32 border-b border-foreground h-8" />
                      </TableCell>
                    </TableRow>
                  ))}
                  {medTasks.length === 0 && (
                    <TableRow>
                      <TableCell colSpan={4} className="text-center py-20 text-muted-foreground font-medium">
                        No active medication requests in the pharmacy queue.
                      </TableCell>
                    </TableRow>
                  )}
                </TableBody>
              </Table>
            </div>
          )}
        </CardContent>
      </Card>

      <div className="hidden print:block pt-12">
        <div className="grid grid-cols-2 gap-20">
          <div className="space-y-12">
            <p className="text-[10px] font-black uppercase tracking-widest">Dispensing Pharmacist</p>
            <div className="border-t border-foreground pt-2">
              <p className="text-xs font-bold">{user?.fullName || user?.username}</p>
              <p className="text-[10px] text-muted-foreground font-bold uppercase tracking-tighter">Registration: {user?.id?.substring(0, 8).toUpperCase()}</p>
            </div>
          </div>
          <div className="space-y-12 text-right">
            <p className="text-[10px] font-black uppercase tracking-widest">Receiving Clinical Staff</p>
            <div className="border-t border-foreground pt-2">
              <p className="text-[10px] text-muted-foreground font-bold">Signature / Timestamp</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
